module.exports = {
  mongoURI: process.env.MONGO_URI,
  cookieKey: process.env.COOKIE_KEY,
  corsOptions: process.env.CORS_OPTIONS,
  redirectDomain: process.env.REDIRECT_DOMAIN,
  nodeMailer: process.env.NODE_MAILER,
  hostURI: process.env.HOST_URI,
  emailSender: process.env.EMAIL_SENDER,
  emailAuth: process.env.EMAIL_AUTH,
  type: process.env.TYPE,
  user: process.env.USER,
  clientId: process.env.CLIENT_ID,
  clientSecret: process.env.CLIENT_SECRET,
  refreshToken: process.env.REFRESH_TOKEN,
  accessToken: process.env.ACCESS_TOKEN,
};
